variables:
  - &docker_creds
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

steps:
  build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: edrodefeld/luna
      auto_tag: true
      <<: *docker_creds
    when:
      - event: [push, manual]
        branch: main

  sync-secrets:
    image: alpine:3.22.2
    environment:
      BAO_ADDR: https://cuneiform.pinwheel.fan
      BAO_TOKEN:
        from_secret: cuneiform_token
    commands:
      # Install dependencies
      - apk add --no-cache curl jq tar
      
      # Install kubectl
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      
      # Install bao CLI
      - curl -L -o bao.tar.gz https://github.com/openbao/openbao/releases/download/v2.1.0/bao_2.1.0_linux_amd64.tar.gz
      - tar -xzf bao.tar.gz
      - chmod +x bao
      
      # Fetch secrets from Cuneiform
      - ./bao kv get -format=json galaxy-kv/prod/luna > /tmp/secrets.json
      
      # Create K8s secret
      - |
        kubectl create secret generic luna-env-secrets \
          --from-literal=PUBLIC_AUTH_URL="$(cat /tmp/secrets.json | jq -r '.data.data.PUBLIC_AUTH_URL')" \
          --from-literal=PUBLIC_API_URL="$(cat /tmp/secrets.json | jq -r '.data.data.PUBLIC_API_URL')" \
          --from-literal=NODE_ENV="$(cat /tmp/secrets.json | jq -r '.data.data.NODE_ENV')" \
          -n galaxy --dry-run=client -o yaml | kubectl apply -f -
    when:
      - event: [push, manual]
        branch: main

  deploy:
    image: bitnami/kubectl
    commands:
      - kubectl rollout restart deployment/luna -n galaxy
    when:
      - event: [push, manual]
        branch: main
